// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwGPIZTYRELp1zTnKQKixyE17L8N4Bp0M',
    appId: '1:153225633940:web:9811b01479f60a06fbd481',
    messagingSenderId: '153225633940',
    projectId: 'school-3dc80',
    authDomain: 'school-3dc80.firebaseapp.com',
    storageBucket: 'school-3dc80.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwGPIZTYRELp1zTnKQKixyE17L8N4Bp0M',
    appId: '1:153225633940:web:9811b01479f60a06fbd481',
    messagingSenderId: '153225633940',
    projectId: 'school-3dc80',
    authDomain: 'school-3dc80.firebaseapp.com',
    storageBucket: 'school-3dc80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwGPIZTYRELp1zTnKQKixyE17L8N4Bp0M',
    appId: '1:153225633940:web:9811b01479f60a06fbd481',
    messagingSenderId: '153225633940',
    projectId: 'school-3dc80',
    authDomain: 'school-3dc80.firebaseapp.com',
    storageBucket: 'school-3dc80.appspot.com',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwGPIZTYRELp1zTnKQKixyE17L8N4Bp0M',
    appId: '1:153225633940:web:9811b01479f60a06fbd481',
    messagingSenderId: '153225633940',
    projectId: 'school-3dc80',
    authDomain: 'school-3dc80.firebaseapp.com',
    storageBucket: 'school-3dc80.appspot.com',
    iosBundleId: 'com.example.first.RunnerTests',
  );
}
